language: julia
os:
- linux
julia:
- 1.4
- nightly
matrix:
allow_failures:
    - julia: nightly
fast_finish: true
notifications:
email: false
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
